version: "3.8"

services:
  falavipmusicplay:
    image: ghcr.io/rafaeljuniorvip/falavipmusicplay:latest
    networks:
      - minha_rede
    volumes:
      - falavipmusicplay_storage:/app/storage
      - falavipmusicplay_db:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.falavipmusicplay.entrypoints=websecure"
        - "traefik.http.routers.falavipmusicplay.rule=Host(`falavipmusic.viptecnologia.com.br`)"
        - "traefik.http.routers.falavipmusicplay.service=falavipmusicplay-service"
        - "traefik.http.routers.falavipmusicplay.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.falavipmusicplay-service.loadbalancer.server.port=8000"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  falavipmusicplay_storage:
    driver: local
  falavipmusicplay_db:
    driver: local

networks:
  minha_rede:
    external: true
